
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "test3@cours.com",
    "password": "test3"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test3@cours.com",
    "password": "test3"
}
###
GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDkwMWY4MTc2NTMwOTUyOTRjMzc2MjciLCJpYXQiOjE2MjAwNTgwMDksImV4cCI6MTYyMDE0NDQwOX0.YhYF-Q1t18v3O-UB9rTKmmbM_1u_AytDkdUkCFQ77GU
###
PUT http://localhost:3000/api/sauces/608fdef2890cc03c5c7b06ad
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDkwMWY4MTc2NTMwOTUyOTRjMzc2MjciLCJpYXQiOjE2MjAwNTgwMDksImV4cCI6MTYyMDE0NDQwOX0.YhYF-Q1t18v3O-UB9rTKmmbM_1u_AytDkdUkCFQ77GU
Content-Type: application/json

{
    "name": "coucou"
}